# When workflow run
on:
  push:
    branches: ["master"]
jobs:
  build:
    name: build and test
    runs-on: windows-latest
    steps:
      - name: HZ cho
        uses: actions/checkout@v3
      - name: Run a one line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo one
          echo two

  depended-build: 
    needs: build
    steps: 
      - run: echo Hi here depended-build

  independed-build:
    steps: 
      - run: echo Hi here independed-build